services:
  - type: web
    name: big5-60p
    env: python
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:$PORT app:app"
    healthCheckPath: /test
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
